# Generated by Django 2.2.4 on 2021-03-29 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('open_mic_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenMic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(max_length=45)),
                ('genre', models.CharField(max_length=45)),
                ('date', models.DateTimeField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('performers', models.ManyToManyField(related_name='openmics', to='open_mic_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('openmic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='open_mic_app.OpenMic')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='open_mic_app.User')),
            ],
        ),
    ]
